Add map sessions endpoint
olab/OLab45-Common pull request #9
Opened 2023-07-07 03:09 UTC by elhardoum

2023-08-04 13:06 UTC, RotateAt60MPH commented on Endpoints/player/MapsEndpoint/MapsEndpoint.cs
> +               cast(from_unixtime(s.start_time) as datetime) as `Timestamp`,
A hard-coded SQL state should not be necessary if EF relationships between entities are set up correctly.  Please investigate.

2023-08-04 13:06 UTC, RotateAt60MPH requested changes
A hard-coded SQL state should not be necessary if EF relationships between entities are set up correctly. Please investigate.

2023-08-09 02:58 UTC, elhardoum reviewed
Updated the query to use LINQ, though the relations are still not fully used (e.g. Session.SessionTraces vs a join)? I can send make another update to spend more time on this to use the relationships instead of joining. At least now it doesn't query the tables via hardcoded names/cols, but rather via the EF properties.

2023-08-13 17:26 UTC, RotateAt60MPH commented
As discussed:

var userSession = await dbContext.UserSessions
  .AsNoTracking()
  .Include(x => x.UserSessionTraces)
  .FirstOrDefaultAsync(x => x.Id == mapId && x.UserId == user.Id && x.Issuer == user.Iss );

2023-08-16 02:00 UTC, elhardoum reviewed
This is now completed. When matching users, the auth issuer will be safely checked, so DT will now also see anonymous users in the session report. I was excluding them before not knowing they were external plays.

2023-08-18 00:54 UTC, RotateAt60MPH approved these changes

2023-08-18 00:54 UTC, merged